const TYPES = {
  START_REQUEST: "START_REQUEST",
  FINISH_REQUEST: "FINISH_REQUEST",

  SIGNUP_KID: "SIGNUP_KID",
  LOGIN_USER: "LOGIN_USER",
  CHANGE_NAME: "CHANGE_NAME",

  //POSTs
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  ADD_POST: "ADD_POST",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_ERROR: "ADD_POST_ERROR",

  //CATEGORIES
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_CATEGORIES_ERROR: "GET_CATEGORIES_ERROR",
};

export default TYPES;
