const TYPES = {
  START_REQUEST: "START_REQUEST",
  FINISH_REQUEST: "FINISH_REQUEST",

  SIGNUP_KID: "SIGNUP_KID",
  LOGIN_USER: "LOGIN_USER",
  GET_PROFILE: "GET_PROFILE",
  CHANGE_NAME: "CHANGE_NAME",

  //POSTs
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  ADD_POST: "ADD_POST",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_ERROR: "ADD_POST_ERROR",

  GET_COMMENTS: "GET_COMMENTS",

  //Product
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",
  SEARCH_PRODUCT_SUCCESS: "SEARCH_PRODUCT_SUCCESS",
  RATE_PRODUCT_SUCCESS: "RATE_PRODUCT_SUCCESS",

  //CATEGORIES

  CHANGE_PAGE_POST: "CHANGE_PAGE_POST",
  CHANGE_PAGE_PRODUCT: "CHANGE_PAGE_PRODUCT",
  ADD_COMMENT: "ADD_COMMENT",

  //CATEGORIES
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_CATEGORIES_ERROR: "GET_CATEGORIES_ERROR",
};

export default TYPES;
