const TYPES = {
  LOGIN_USER: "LOGIN_USER",
  CHANGE_NAME: "CHANGE_NAME",

  //POSTs
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  ADD_POST: "ADD_POST",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_ERROR: "ADD_POST_ERROR"
};

export default TYPES;
